### ISSUE TITLE
Class 'NorseBlue\ExtensibleObjects\Resolvers\ClassConstructorAccessibleResolver' not found

### ISSUE THREAD

**Issue by peter279k** [norse-blue/php-object-facades#2]
**Describe the bug**

The detailed error message is as follows:

```
There was 1 error:
1) NorseBlue\ObjectFacades\Tests\Facades\FacadeTest::can_call_object_method_from_facade
Error: Class 'NorseBlue\ExtensibleObjects\Resolvers\ClassConstructorAccessibleResolver' not found
/home/travis/build/norse-blue/php-object-facades/src/Resolvers/TargetClassCreateResolver.php:25
/home/travis/build/norse-blue/php-object-facades/src/Facade.php:57
/home/travis/build/norse-blue/php-object-facades/tests/Facades/FacadeTest.php:27
```

**Environment**
Include as many relevant details about the environment you experienced the bug in and how to reproduce it.
- Versions used: `PHP 7.3`.
- Operating system and version: `Ubuntu 18.04`.

**To Reproduce**
1. Clone this repository on master branch
2. Run `php7.3 ~/composer.phar install`
3. Run `php7.3 vendor/bin/phpunit` 
4. See fatal error message

**Expected behavior**

The unit tests should be completed without any error message.

**Screenshots**
There is no screenshot at this moment.

**Additional context**
The current problem is about this class has been changed or removed.

And this package depends on [php-extensible-objects](https://github.com/norse-blue/php-extensible-objects/tree/master/src/Resolvers).

And it's also the reason why the Travis CI build is failed.

The latest Travis CI build log is [here](https://travis-ci.com/norse-blue/php-object-facades/jobs/232756658).

**Comment by axelitus** [comment]
I can confirm this is an issue.

I'm currently working on this package to fix the issues introduced by some changes on the dependencies.

I hope I get this fixed in the next few days.

**Comment by axelitus** [comment]
This issue has been fixed on the master branch. The test build is [green again](https://travis-ci.com/norse-blue/php-object-facades/builds/127410312).
